### ISSUE TITLE
Can this be customized for ePub (any) file formats?

### ISSUE THREAD

**Issue by vividcode** [michaelnmmeyer/gutenberg#2]
Firstly, a great repo! ❤️

I was wondering if this could be customized not just for text format but any eBook format. I see that this is taken care of inside this function: 

`find_nodes(file, "dcterms:format/rdf:Description/rdf:value")`

I could have tweaked a PR myself but I have no knowledge of Gutenberg RDF and very basic idea of python.

Would be a greatly helpful addition....

**Comment by michaelnmmeyer** [comment]
Hello Nirav.

Unfortunately, adding support for other formats while preserving the same features (in particular the auto-update thing) would require quite a bit of work, which I really don't have time for at the moment.

That said, in the vast majority of cases (maybe even in all cases, I don't remember the details), download URLs of epub files follow the format www.gutenberg.org/ebooks/$ident.epub, where $ident is the ebook identifier. Since ebook identifiers are returned by the `gutenberg search` command (under the `key` field), you can massage the output of this command and download the epub files with an external tool.

For instance, to download epubs about Berlin, you can do the following (with the [`jq`](https://stedolan.github.io/jq/) tool):

    gutenberg search berlin | jq '.key' | while read key; do
        wget www.gutenberg.org/ebooks/$key.epub;
    done

Note however that this won't find epubs that aren't also available as plain text, and that some ebooks in plain text might not be available in the epub format.

**Comment by vividcode** [comment]
Thank you for the guidelines, Michael! I will surely try out that method.
